apiVersion: v1
kind: Service
metadata:
  name: service-db
  labels:
    app: service-db
    service: service
spec:
  selector:
    app: service-db
    service: service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP