apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: {{ name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  labels:
    app: {{ app }}
    service: {{ service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ app }}
      service: {{ service_name }}
  template:
    metadata:
      labels:
        app: {{ app }}
        service: {{ service_name }}
    spec:
      serviceAccountName: {{ name }}
      {{ volume }}
      containers:
      - name: {{ name }}-container
        image: {{ image }}
        ports:
        - containerPort: {{ port }}
        {{ volume_mount }}
        env: {{ deployment_variables}}